### GET - Categorias ###
GET http://localhost:5000/api/v1/categories HTTP/1.1

### GET - Cursos ###
GET http://localhost:5000/api/v1/courses HTTP/1.1

### GET - Grau de instrução ###
GET http://localhost:5000/api/v1/degrees HTTP/1.1

### GET - Áreas de conhecimentos ###
GET http://localhost:5000/api/v1/areas HTTP/1.1

### GET - Grau de instrução ###
GET http://localhost:5000/api/v1/degrees HTTP/1.1