GET http://localhost:5000/helloclass HTTP/1.1

POST http://localhost:5000/user HTTP/1.1
Content-Type: : application/json

{
    "user_email":"user@test.com",
    "password":"mysecret",
    "name":"User Test",
    "type_user":1,
    "university":"{'text':'Universidade Federal do Maranhão', 'value':'1'}",
    "degree":"{'text':'Graduação', 'value':'1'}",
    "course":"{'text':'Universidade Federal do Maranhão','value':'1'}"
}