GET http://localhost:5000/hello HTTP/1.1

POST http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "email":"user@example.com",
    "password":"mypass",
    "name":"name",
    "type_user":1,
    "university":"{'text':'Universidade Federal do Maranhão', 'value':'1'}",
    "degree":"{'text':'Graduação', 'value':'1'}",
    "course":"{'text':'Engenharia da Computação', 'value':'1'}"
}